import type { MenuItem } from "./types.js";
import type { MenuRegistry } from "./menu.js";

const SHELLS = ["bash", "fish", "zsh"] as const;

export type CompletionShell = (typeof SHELLS)[number];

interface CompletionValue {
  readonly value: string;
  readonly description?: string;
}

interface CompletionCommand {
  readonly name: string;
  readonly description: string;
  readonly children?: readonly CompletionCommand[];
  readonly values?: readonly CompletionValue[];
}

const helpOptions = ["-h", "--help"] as const;
const todoOptions = ["--bar-json", "--count", "--all"] as const;
const shellValues: readonly CompletionValue[] = SHELLS.map((shell) => ({
  value: shell,
  description: `${shell[0].toUpperCase()}${shell.slice(1)}`,
}));

const nativeCommands: readonly CompletionCommand[] = [
  {
    name: "test-connection",
    description: "Diagnose Home Assistant connectivity",
  },
  {
    name: "test-view",
    description: "Open the TUI sandbox view",
  },
  {
    name: "completions",
    description: "Print shell completions",
    values: shellValues,
  },
];

function isCompletionShell(shell: string): shell is CompletionShell {
  return (SHELLS as readonly string[]).includes(shell);
}

function shellList(): string {
  return SHELLS.join(", ");
}

function bashQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function fishQuote(value: string): string {
  return `'${value.replaceAll("\\", "\\\\").replaceAll("'", "\\'")}'`;
}

function zshQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function commandName(value: string): string {
  return value.replace(/[^A-Za-z0-9_]/g, "_");
}

function isCliAddressable(item: MenuItem): boolean {
  return item.action.type !== "noop" && item.action.type !== "quit";
}

function menuCommand(item: MenuItem): CompletionCommand {
  return {
    name: item.id.split(".").at(-1) ?? item.id,
    description: item.description,
  };
}

function menuCommands(menu: MenuRegistry): readonly CompletionCommand[] {
  return menu.mainMenuItems.filter(isCliAddressable).map((item) => {
    const children = menu.submenus
      .get(item.id)
      ?.filter(isCliAddressable)
      .map(menuCommand);
    return {
      name: item.id,
      description: item.description,
      ...(children && children.length > 0 ? { children } : {}),
    };
  });
}

function completionCommands(menu: MenuRegistry): readonly CompletionCommand[] {
  return [...menuCommands(menu), ...nativeCommands];
}

function commandEntries(
  commands: readonly CompletionCommand[],
): readonly string[] {
  return commands.map((command) => `${command.name}:${command.description}`);
}

function valueEntries(values: readonly CompletionValue[]): readonly string[] {
  return values.map((value) =>
    value.description ? `${value.value}:${value.description}` : value.value,
  );
}

function renderBashCompletions(menu: MenuRegistry): string {
  const commands = completionCommands(menu);
  const topLevelWords = [
    ...commands.map((command) => command.name),
    ...helpOptions,
  ];
  const todoOptionWords = [...helpOptions, ...todoOptions].join(" ");
  const branches = commands.flatMap((command) => {
    const words =
      command.children?.map((child) => child.name) ??
      command.values?.map((value) => value.value);
    if (!words || words.length === 0) return [];
    return [
      `    ${command.name})`,
      "      if (( cword == 2 )); then",
      `        COMPREPLY=( $(compgen -W ${bashQuote(words.join(" "))} -- "$cur") )`,
      "      fi",
      "      return",
      "      ;;",
    ];
  });

  return [
    "# bash completion for home-assistant-tui",
    "# Generated by home-assistant-tui completions bash.",
    "",
    "_home_assistant_tui() {",
    "  local cur cword",
    "  COMPREPLY=()",
    "  cur=${COMP_WORDS[COMP_CWORD]}",
    "  cword=$COMP_CWORD",
    "",
    "  if [[ $cur == -* ]]; then",
    "    if [[ ${COMP_WORDS[1]-} == todo ]]; then",
    `      COMPREPLY=( $(compgen -W ${bashQuote(todoOptionWords)} -- "$cur") )`,
    "      return",
    "    fi",
    `    COMPREPLY=( $(compgen -W ${bashQuote(helpOptions.join(" "))} -- "$cur") )`,
    "    return",
    "  fi",
    "",
    "  case ${COMP_WORDS[1]-} in",
    ...branches,
    "  esac",
    "",
    "  if (( cword == 1 )); then",
    `    COMPREPLY=( $(compgen -W ${bashQuote(topLevelWords.join(" "))} -- "$cur") )`,
    "  fi",
    "}",
    "",
    "complete -F _home_assistant_tui home-assistant-tui",
    "",
  ].join("\n");
}

function renderFishCompletions(menu: MenuRegistry): string {
  const commands = completionCommands(menu);
  const lines = [
    "# fish completion for home-assistant-tui",
    "# Generated by home-assistant-tui completions fish.",
    "",
    "complete -c home-assistant-tui -f",
    "complete -c home-assistant-tui -s h -l help -d 'Show help message'",
    "complete -c home-assistant-tui -n '__fish_seen_subcommand_from todo' -l bar-json -d 'Print todo status-bar JSON'",
    "complete -c home-assistant-tui -n '__fish_seen_subcommand_from todo' -l count -d 'Print todo item count'",
    "complete -c home-assistant-tui -n '__fish_seen_subcommand_from todo' -l all -d 'Include completed todo items'",
  ];

  for (const command of commands) {
    lines.push(
      `complete -c home-assistant-tui -n '__fish_use_subcommand' -a ${fishQuote(command.name)} -d ${fishQuote(command.description)}`,
    );
    for (const child of command.children ?? []) {
      lines.push(
        `complete -c home-assistant-tui -n '__fish_seen_subcommand_from ${command.name}; and not __fish_seen_subcommand_from ${child.name}' -a ${fishQuote(child.name)} -d ${fishQuote(child.description)}`,
      );
    }
    if (command.values) {
      const values = command.values.map((value) => value.value).join(" ");
      for (const value of command.values) {
        lines.push(
          `complete -c home-assistant-tui -n '__fish_seen_subcommand_from ${command.name}; and not __fish_seen_subcommand_from ${values}' -a ${fishQuote(value.value)} -d ${fishQuote(value.description ?? value.value)}`,
        );
      }
    }
  }

  return `${lines.join("\n")}\n`;
}

function renderZshCompletions(menu: MenuRegistry): string {
  const commands = completionCommands(menu);
  const todoOptionEntries = valueEntries([
    { value: "--bar-json", description: "Print todo status-bar JSON" },
    { value: "--count", description: "Print todo item count" },
    { value: "--all", description: "Include completed todo items" },
  ]);
  const branchArrays = commands.flatMap((command) => {
    const entries = command.children
      ? commandEntries(command.children)
      : command.values
        ? valueEntries(command.values)
        : undefined;
    if (!entries) return [];
    const arrayName = `_home_assistant_tui_${commandName(command.name)}_values`;
    return [
      `local -a ${arrayName}`,
      `${arrayName}=(`,
      ...entries.map((entry) => `  ${zshQuote(entry)}`),
      ")",
      "",
    ];
  });
  const branchCases = commands.flatMap((command) => {
    if (!command.children && !command.values) return [];
    const arrayName = `_home_assistant_tui_${commandName(command.name)}_values`;
    const label = command.values ? "value" : `${command.name} command`;
    return [
      `    ${command.name})`,
      "      if (( CURRENT == 3 )); then",
      `        _describe -t commands ${zshQuote(label)} ${arrayName}`,
      "        return",
      "      fi",
      "      ;;",
    ];
  });

  return [
    "#compdef home-assistant-tui",
    "# Generated by home-assistant-tui completions zsh.",
    "",
    "local -a _home_assistant_tui_commands",
    "_home_assistant_tui_commands=(",
    ...commandEntries(commands).map((entry) => `  ${zshQuote(entry)}`),
    ")",
    "",
    "local -a _home_assistant_tui_todo_options",
    "_home_assistant_tui_todo_options=(",
    ...todoOptionEntries.map((entry) => `  ${zshQuote(entry)}`),
    ")",
    "",
    ...branchArrays,
    "if (( CURRENT > 2 )) && [[ ${words[2]} == todo && ${words[CURRENT]} == --* ]]; then",
    "  _describe -t options 'todo option' _home_assistant_tui_todo_options",
    "  return",
    "fi",
    "",
    "if (( CURRENT > 2 )) && [[ ${words[CURRENT]} != -* ]]; then",
    "  case ${words[2]} in",
    ...branchCases,
    "  esac",
    "fi",
    "",
    "local state",
    ` _arguments -C -S ${"\\"}`.trimStart(),
    "  '(-h --help)-h[Show help message]' \\",
    "  '(-h --help)--help[Show help message]' \\",
    "  '1:home-assistant-tui command:->command' && return",
    "",
    "case $state in",
    "  command)",
    "    _describe -t commands 'home-assistant-tui command' _home_assistant_tui_commands",
    "    ;;",
    "esac",
    "",
  ].join("\n");
}

/** Return the completion shell requested by CLI args, defaulting to Zsh. */
export function parseCompletionShell(args: readonly string[]): CompletionShell {
  const shell = args.find((arg) => !arg.startsWith("-")) ?? "zsh";
  if (isCompletionShell(shell)) return shell;
  console.error(
    `home-assistant-tui completions: unsupported shell '${shell}' (expected: ${shellList()})`,
  );
  process.exit(1);
}

/** Print help for the completions subcommand. */
export function printCompletionsHelp(): void {
  console.log(`Usage: home-assistant-tui completions [bash|fish|zsh]

Print shell completions for home-assistant-tui.

Examples:
  home-assistant-tui completions zsh
  home-assistant-tui completions bash
  home-assistant-tui completions fish`);
}

/** Render shell completions for the selected shell. */
export function renderCompletions(
  shell: CompletionShell,
  menu: MenuRegistry,
): string {
  switch (shell) {
    case "bash":
      return renderBashCompletions(menu);
    case "fish":
      return renderFishCompletions(menu);
    case "zsh":
      return renderZshCompletions(menu);
  }
}
